### ISSUE TITLE
Overflow field is missing 

### ISSUE THREAD

**Issue by BigJerBD** [lzhuor/auto_size_text_field#1]
Hello, 

I'm using version 0.1.5 and I've noticed that the overflow field does not exists despite the documentation mentioning it. 

If this is normal, how can I handle overflow properly with this package?

thanks =)

**Comment by lzhuor** [comment]
Thanks @BigJerBD , it was copied from `auto_size_text` which it's only available in `Text` and `Text.rich` widget. Will remove them.

**Comment by lzhuor** [comment]
Closed because `overflow` is not available in `TextField`
