### ISSUE TITLE
Update to null safety?

### ISSUE THREAD

**Issue by Arenukvern** [lzhuor/auto_size_text_field#12]
First of all, thank you for your package!

And the question:
As Flutter brings a sound of null safety ([please see at the link](https://medium.com/dartlang/announcing-dart-null-safety-beta-87610fee6730)), is this package will support null safety in future?

**Comment by Sameerkash** [comment]
if there's no WIP on this, I'd be happy to make a PR

**Comment by lzhuor** [comment]
Hi @Sameerkash , thank you! People will love it. Happy to review the PR. I am a bit occupied by my day job a the moment but would love to review the PR and contribute.

**Comment by Sameerkash** [comment]
@lzhuor, great!, I'm on it. will be up within the next couple of days.

**Comment by lzhuor** [comment]
Thank you! Merged the PR into master. You can start using it with git ssh before I publish a new version in pub.dev.

**Comment by lzhuor** [comment]
@Sameerkash You can access the nullsafety version from https://pub.dev/packages/auto_size_text_field/versions/1.0.0-nullsafety.1 now. 

Thanks again for the contribution! 🚀
