### ISSUE TITLE
Contents padding consideration and multiline use

### ISSUE THREAD

**Issue by hyobbb** [lzhuor/auto_size_text_field#14]
Hi. 

I found that when there's contents padding in input decoration parameter it doesn't expand enough to show every text.
so I added some code at the end of  "_checkTextFits" functions like below.

```
 double _width = tp.width;
    double _height = tp.height;
    if(widget.decoration.contentPadding!=null){
      _width = tp.width + widget.decoration.contentPadding.horizontal;
      _height = tp.height + widget.decoration.contentPadding.vertical;
    }

    //_textSpanWidth = math.max(tp.width, widget.minWidth ?? 0);
    _textSpanWidth = math.max(_width, widget.minWidth ?? 0);

    return !(tp.didExceedMaxLines ||
        _height >= constraints.maxHeight - 30 ||
        _width >= constraints.maxWidth);
```

For comparing height I added extra value 30 more because when there's multi line input it doesn't expand enough vertically.
In general, when you put maxLines = null and keyboardType = TextInputType.multiline, it behaves badly. For example
```

Container(
              constraints: BoxConstraints(
                maxHeight: 380,
                maxWidth: 380,
              ),
              decoration: BoxDecoration(
                border: Border.all(width: 2, color: Colors.amber),
              ),
              child: AutoSizeTextField(
                controller: _textEditingControllerOne,
                fullwidth: false,
                autofocus: true,
                minFontSize: 0,
                maxLines: null,
                style: TextStyle(fontSize: 60),
                textAlignVertical: TextAlignVertical.center,
                decoration: InputDecoration(
                  border: InputBorder.none,
                  isDense: true,
                  contentPadding: const EdgeInsets.all(10)
                ),
                keyboardType: TextInputType.multiline,
              ),
            ),
```

this is what I am testing for multiline input without minimum font so that users can type text without limitation.
I think for multiline text,  checking algorithm to adjust fontsize should be changed.
because until the textfield expand as big as it's constraints size the given fontsize should be maintained. So in that case height and width condition should be AND. 

 ```
 _height >= constraints.maxHeight - 30 &&
        _width >= constraints.maxWidth
```

Still, It has issues for multi line use so I will dig it more.
If anyone has an idea please let me know.

**Comment by hyobbb** [comment]
modified version is in my fork

https://github.com/hyobbb/auto_size_text_field.git

**Comment by lzhuor** [comment]
Hi @hyobbb , thank you for the detailed analysis. Do you mind creating a PR so folks can review it and merge it once everything works out?

**Comment by hyobbb** [comment]
Ok. Right now I can't afford it but maybe in 2~3weeks I could pull request. Let you know then. Thanks!
