### ISSUE TITLE
Bug - Parameter missing

### ISSUE THREAD

**Issue by foresourcedev** [lzhuor/auto_size_text_field#28]
Get this error message on building version 1.0.1:

../../.pub-cache/hosted/[pub.dartlang.org/auto_size_text_field-1.0.1/lib/src/auto_size_text_field.dart:603:9](http://pub.dartlang.org/auto_size_text_field-1.0.1/lib/src/auto_size_text_field.dart:603:9):
Error: No named parameter with the name 'maxLengthEnforced'.
        maxLengthEnforced: widget.maxLengthEnforced,
        ^^^^^^^^^^^^^^^^^

**Comment by lzhuor** [comment]
Hi @foresourcedev , could you please share the `flutter doctor` result? Thank you!

**Comment by stepushchik-denis-gismart** [comment]
I have the same issue.

```
[✓] Flutter (Channel stable, 3.0.0, on macOS 11.6 20G165 darwin-x64, locale en-BY)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] VS Code (version 1.66.2)
[✓] Connected device (3 available)
[✓] HTTP Host Availability
```

**Comment by ashemetov** [comment]
Same issue. Happened after migration to Flutter 3.0, Flutter 2.5 works fine.

**Comment by JCFowler** [comment]
Also having this issue after updating to Flutter 3.0

**Comment by stepushchik-denis-gismart** [comment]
I fixed in #29

**Comment by Amal92** [comment]
> Same issue. Happened after migration to Flutter 3.0, Flutter 2.5 works fine.

Same here. Downgraded flutter to 2.10.5, then the library worked.

**Comment by lzhuor** [comment]
Thank you, folks. Merged #29 kudos to @stepushchik-denis-gismart .

I will cut a release later today.

**Comment by lzhuor** [comment]
Released. Thank you, folks!

**Comment by Ronjack** [comment]
thx

**Comment by foresourcedev** [comment]
Here it is.  Please let me know if you need anything further.


Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, 2.13.0-0.3.pre, on macOS 11.6.5 20G527
darwin-x64, locale en)
[✓] Android toolchain - develop for Android devices (Android SDK version
33.0.0-rc2)
[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.1)
[✓] Android Studio (version 2020.3)
[✓] IntelliJ IDEA Ultimate Edition (version 2022.1)
[✓] IntelliJ IDEA Ultimate Edition (version 2022.1)
[✓] IntelliJ IDEA Ultimate Edition (version 2021.3.1)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

• No issues found!
